name: CI
on:
push: 
branches: [ main ]
pull_request:
branches: [ main ]
jobs:
smoke-test:
runs-on: ubuntu-latest
steps:
-name: checkout code
uses: actions/checkout@v3
-name: Install dependencies
run: |
python ai_integration_demo.py tests/sample_transcript.txt
